name: Typecheck and ESLint

on: [push, pull_request]

env:
  SKIP_ENV_VALIDATION: 1

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Ensure types are valid
        run: pnpm run lint:typescript

      - name: Run ESLint
        run: pnpm run lint
